---
version: '3.1'

services:

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ${JENKINS_HOME}:/var/jenkins_home

  sonarqube:
    image: sonarqube:9-community
    container_name: sonarqube
    restart: always
    ports:
      - 9000:9000
    platform: linux/x86_64
...